name: refah
description: health app.

#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7

environment:
 sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  adobe_xd: ^1.0.0
  flutter_svg: ^0.18.0
  carousel_slider: ^2.3.1
  dotted_border: ^1.0.6
  dio: ^3.0.10
  shared_preferences: ^0.5.12
  http: ^0.12.2
  encrypt: ^4.0.3
  image_picker: ^0.6.7+11
  permission_handler: ^5.0.1+1
  awesome_dialog: ^1.2.0
  jalali_calendar: ^1.0.3+1
  intl: ^0.16.1
  url_launcher: ^5.7.2
  package_info: ^0.4.3
  flutter_launcher_icons: ^0.8.0
  flutter_mobile_carousel: ^1.0.3
  flutter_rating_bar: ^3.0.1+1
  slide_popup_dialog: ^0.0.2
  hawk_fab_menu: ^0.3.2
  flutter_plugin_android_lifecycle: ^1.0.11
  signalr_core: ^1.0.5
  rxdart: ^0.24.1
  # awesome_notifications: ^0.0.2+2
  font_awesome_flutter: ^8.8.1
  fluttertoast: ^4.0.1
  path_provider: ^1.4.0
  progressive_image: ^1.0.1
  bitmap: ^0.0.6
  palette_generator: ^0.2.3
  flutter_circular_slider: ^2.5.0
  flutter_local_notifications: ^1.4.4+5
  darq: ^0.4.0+1

dev_dependencies:
  flutter_driver:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/refahlogo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/smallgreenheader.png
    - images/dentistry.png
    - images/familyinsurance.png
    - images/cards.png
    - images/priceoffer.png
    - images/BigGreenHeader.png
    - images/stickingplaster.png
    - images/backarrow.svg
    - images/BigHeader.png
    - images/banner.png
    - images/female_avatar.jpg
    - images/ballonbackground.png
    - images/doshed.svg
    - images/call.svg
    - images/edit.svg
    - images/confirm.svg
    - images/reject.svg
    - images/sent.png
    - images/comment.svg
    - jsons/fa.json
    - images/dentistry1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IRANSans
      fonts:
        - asset: fonts/iransans.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
